//@version=5
indicator("IDM Detector", overlay=true)

bullish_idm = low < low[1] and close > math.max(open[1], close[1])
bearish_idm = high > high[1] and close < math.min(open[1], close[1])

var float idm_price = na
var int idm_bar = na

if bearish_idm
    idm_price := high
    idm_bar := bar_index
if bullish_idm
    idm_price := low
    idm_bar := bar_index

if not na(idm_price) and bearish_idm
    if high >= idm_price or low <= idm_price
        line.new(idm_bar, idm_price, bar_index, idm_price, color=color.red, width=1)

if not na(idm_price) and bullish_idm
    if high >= idm_price or low <= idm_price
        line.new(idm_bar, idm_price, bar_index, idm_price, color=color.green, width=1)


if bullish_idm
    label.new(bar_index, low, "X", color=color.green, style= label.style_label_up, textcolor=color.white)
if bearish_idm
    label.new(bar_index, high, "X", color=color.red, style=label.style_label_down, textcolor=color.white)